# Generated by Django 4.1.1 on 2022-09-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_alter_reservation_cleaner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="service_time",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
