# Generated by Django 4.1.1 on 2022-09-09 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_alter_reservation_service_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="reservation",
            name="service_time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservations.servicetime",
            ),
        ),
    ]
