# Generated by Django 4.1.1 on 2022-09-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_servicetime_alter_reservation_service_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicetime",
            name="time",
        ),
    ]
