# Generated by Django 4.1.1 on 2022-09-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_remove_servicetime_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetime",
            name="time",
            field=models.CharField(
                choices=[("9AM", "9AM"), ("10AM", "10AM"), ("11AM", "11AM")],
                max_length=4,
                null=True,
            ),
        ),
    ]
