# Generated by Django 4.1.1 on 2022-09-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0006_servicetime_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetime",
            name="time",
            field=models.CharField(
                choices=[("Nine AM", "9AM"), ("Ten AM", "10AM"), ("Eleven AM", "11AM")],
                max_length=20,
                null=True,
            ),
        ),
    ]
