# Generated by Django 4.1.1 on 2022-09-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0008_alter_reservation_service_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="service_time",
            field=models.CharField(
                blank=True,
                choices=[("9AM", "9AM"), ("10AM", "10AM"), ("11AM", "11AM")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="ServiceTime",
        ),
    ]
