# Generated by Django 4.1.1 on 2022-09-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0012_remove_reservation_service_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Time",
        ),
    ]
