# Generated by Django 4.1.1 on 2022-09-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0014_remove_reservation_apt_num_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="service_time",
        ),
    ]
