# Generated by Django 4.1.1 on 2022-09-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0015_remove_reservation_service_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="service_time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
