# Generated by Django 4.1.1 on 2022-09-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0016_reservation_service_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="service_time",
        ),
    ]
