# Generated by Django 4.1.1 on 2022-09-20 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0017_remove_reservation_service_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservations.address",
            ),
        ),
    ]
